### ISSUE TITLE
docz has been moved to docz org

### ISSUE THREAD

**Issue by itaditya** [siddhant1/get-that-issue#13]
Currently the docz repo is pointing to `pedronauck/docz` https://github.com/siddhant1/get-that-issue/blob/master/src/data/projects.js#L112

but docz has been moved to https://github.com/doczjs/docz

The `projects.js` file should be updated

**Comment by Srihari44** [comment]
I'll do this one.

**Comment by Srihari44** [comment]
> I'll do this one.

#19

**Comment by Srihari44** [comment]
Done #19

**Comment by siddhant1** [comment]
Thanks!
