### ISSUE TITLE
Host the background image on https

### ISSUE THREAD

**Issue by itaditya** [siddhant1/get-that-issue#15]
Currently the background image is loaded from http://thecodeplayer.com/uploads/media/geometry.png

which is an HTTP url whereas the website is HTTPS. Due to this the browser shows Mix-Content warning and the page doesn't get a green lock which is a must have these days for security purposes.

<img width="1680" alt="Screenshot 2019-10-05 at 7 48 25 PM" src="https://user-images.githubusercontent.com/15871340/66256222-39fecd00-e7a9-11e9-82e2-2556a866bc19.png">

**Comment by siddhant1** [comment]
Closing! Fixed
