### ISSUE TITLE
Time period on issues.

### ISSUE THREAD

**Issue by gc-o** [siddhant1/get-that-issue#2]
This is an amazing project!

I just have one piece of feedback, sometimes, issues are quite old.  Could there be a way to select a time frame or limit issues to a certain periods like within 6 months up to now?

**Comment by siddhant1** [comment]
Looks like a great improvement ! I will work on this later , I think I should also move the dependency from good-first-issue module.

**Comment by siddhant1** [comment]
Let's keep this open , I will work on this
Thanks
